export const absExercises: Exercise[] = [
  {
    id: "plank",
    name: "Plank",
    description:
      "A static hold exercise where you support your body weight on your forearms and toes, engaging the core.",
    muscleGroups: [
      "rectus abdominis",
      "transverse abdominis",
      "obliques",
      "lower back",
    ],
    difficulty: "beginner",
    equipment: [],
    can_train_at_home: true,
    bodyweight: true,
    compound: false,
    unilateral: false,
    hasDuration: true,
  },
  {
    id: "crunch",
    name: "Crunch",
    description:
      "A core exercise where you lift your upper back off the ground while keeping your lower back on the floor.",
    muscleGroups: ["rectus abdominis"],
    difficulty: "beginner",
    equipment: [],
    can_train_at_home: true,
    bodyweight: true,
    compound: false,
    unilateral: false,
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    description:
      "A rotational core exercise where you twist your torso from side to side while seated.",
    muscleGroups: ["obliques", "rectus abdominis"],
    difficulty: "beginner",
    equipment: ["medicine ball", "dumbbell"],
    can_train_at_home: true,
    bodyweight: true,
    compound: false,
    unilateral: false,
  },
  {
    id: "leg-raise",
    name: "Leg Raise",
    description:
      "A lower-abdominal exercise where you lift your legs while lying on your back.",
    muscleGroups: ["lower rectus abdominis"],
    difficulty: "beginner",
    equipment: [],
    can_train_at_home: true,
    bodyweight: true,
    compound: false,
    unilateral: false,
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    description:
      "A dynamic crunch variation where you alternate bringing opposite elbows and knees together.",
    muscleGroups: ["rectus abdominis", "obliques"],
    difficulty: "beginner",
    equipment: [],
    can_train_at_home: true,
    bodyweight: true,
    compound: false,
    unilateral: true,
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    description:
      "An advanced core exercise where you raise your legs while hanging from a bar.",
    muscleGroups: ["rectus abdominis", "hip flexors"],
    difficulty: "intermediate",
    equipment: ["pull-up bar"],
    can_train_at_home: false,
    bodyweight: true,
    compound: false,
    unilateral: false,
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    description:
      "A challenging core exercise where you extend and retract using an ab wheel, engaging the entire core.",
    muscleGroups: ["rectus abdominis", "transverse abdominis", "lower back"],
    difficulty: "intermediate",
    equipment: ["ab wheel"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "side-plank",
    name: "Side Plank",
    description:
      "A core stability exercise where you balance on one forearm and the side of your foot to target the obliques.",
    muscleGroups: ["obliques", "transverse abdominis"],
    difficulty: "beginner",
    equipment: [],
    can_train_at_home: true,
    bodyweight: true,
    compound: false,
    unilateral: true,
    hasDuration: true,
  },
];
