export const backExercises: Exercise[] = [
  {
    id: "pull-up",
    name: "Pull-Ups / Chin-Ups",
    description:
      "A bodyweight exercise where you pull yourself up on a bar until your chin is above it.",
    muscleGroups: ["latissimus dorsi", "biceps", "upper back"],
    difficulty: "intermediate",
    equipment: ["pull-up bar"],
    can_train_at_home: true,
    bodyweight: true,
    compound: true,
    unilateral: false,
    image: "back.jpg",
    importance: 0.1,
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldowns",
    description:
      "A cable machine exercise where you pull a bar down to your chest, mimicking a pull-up motion.",
    muscleGroups: ["latissimus dorsi", "biceps", "upper back"],
    difficulty: "beginner",
    equipment: ["cable machine"],
    can_train_at_home: false,
    bodyweight: false,
    compound: true,
    unilateral: false,
  },
  {
    id: "bent-over-barbell-row",
    name: "Bent-Over Barbell Rows",
    description:
      "A barbell exercise where you hinge at the hips and pull the bar toward your lower ribs.",
    muscleGroups: ["latissimus dorsi", "traps", "rhomboids", "rear delts"],
    difficulty: "intermediate",
    equipment: ["barbell"],
    can_train_at_home: false,
    bodyweight: false,
    compound: true,
    unilateral: false,
    image: "back1.jpg",
  },
  {
    id: "dumbbell-row",
    name: "Dumbbell Rows",
    description:
      "A unilateral movement where you row a dumbbell towards your waist while supporting yourself with the other arm.",
    muscleGroups: ["latissimus dorsi", "rhomboids", "traps"],
    difficulty: "beginner",
    equipment: ["dumbbell"],
    can_train_at_home: true,
    bodyweight: false,
    compound: true,
    unilateral: true,
    image: "back1.jpg",
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Rows",
    description:
      "A machine exercise where you pull a handle towards your torso while seated.",
    muscleGroups: ["latissimus dorsi", "rhomboids", "traps"],
    difficulty: "beginner",
    equipment: ["cable machine"],
    can_train_at_home: false,
    bodyweight: false,
    compound: true,
    unilateral: false,
    image: "back1.jpg",
  },
  {
    id: "deadlift",
    name: "Deadlifts",
    description:
      "A full-body exercise where you lift a barbell from the ground to a standing position.",
    muscleGroups: ["lower back", "glutes", "hamstrings", "traps"],
    difficulty: "intermediate",
    equipment: ["barbell"],
    can_train_at_home: false,
    bodyweight: false,
    compound: true,
    unilateral: false,
    image: "back1.jpg",
    importance: 0.1,
  },
  {
    id: "face-pull",
    name: "Face Pulls",
    description:
      "A cable exercise where you pull a rope attachment toward your face to strengthen the rear delts and upper back.",
    muscleGroups: ["rear delts", "traps", "rhomboids"],
    difficulty: "beginner",
    equipment: ["cable machine"],
    can_train_at_home: false,
    bodyweight: false,
    compound: false,
    unilateral: false,
    image: "upperback.jpg",
  },
  {
    id: "t-bar-row",
    name: "T-Bar Rows",
    description:
      "A barbell row variation where you pull a bar anchored at one end toward your torso.",
    muscleGroups: ["latissimus dorsi", "traps", "rhomboids"],
    difficulty: "intermediate",
    equipment: ["barbell", "T-bar row machine"],
    can_train_at_home: false,
    bodyweight: false,
    compound: true,
    unilateral: false,
    image: "back1.jpg",
  },
  {
    id: "reverse-fly",
    name: "Reverse Flies",
    description:
      "An isolation exercise where you extend your arms out to the sides to strengthen the rear delts and upper back.",
    muscleGroups: ["rear delts", "rhomboids", "traps"],
    difficulty: "beginner",
    equipment: ["dumbbells", "cable machine"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
    image: "upperback.jpg",
    importance: 0.5,
  },
  {
    id: "superman-hold",
    name: "Superman Holds",
    description:
      "A bodyweight exercise where you lift your arms and legs off the ground while lying on your stomach to target the lower back.",
    muscleGroups: ["lower back", "glutes", "hamstrings"],
    difficulty: "beginner",
    equipment: [],
    can_train_at_home: true,
    bodyweight: true,
    compound: false,
    unilateral: false,
    importance: 0.1,
  },
  {
    id: "single-arm-cable-row",
    name: "Single-Arm Cable Rows",
    description:
      "A single-arm cable machine exercise where you pull a handle towards your torso while seated.",
    muscleGroups: ["latissimus dorsi", "rhomboids", "traps"],
    difficulty: "beginner",
    equipment: ["cable machine"],
    can_train_at_home: false,
    bodyweight: false,
    compound: true,
    unilateral: true,
  },
];
