export const forearmExercises: Exercise[] = [
  {
    id: "wrist-curls",
    name: "Wrist Curls",
    description:
      "A seated exercise where you curl a dumbbell or barbell using only your wrists to strengthen the forearm flexors.",
    muscleGroups: ["forearm flexors"],
    difficulty: "beginner",
    equipment: ["barbell", "dumbbells"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "reverse-wrist-curls",
    name: "Reverse Wrist Curls",
    description:
      "A variation of wrist curls where you curl the weight upward to target the forearm extensors.",
    muscleGroups: ["forearm extensors"],
    difficulty: "beginner",
    equipment: ["barbell", "dumbbells"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "farmer's-walk",
    name: "Farmer's Walk",
    description:
      "A grip-strengthening exercise where you walk while holding heavy dumbbells or kettlebells.",
    muscleGroups: ["forearms", "grip strength", "shoulders"],
    difficulty: "beginner",
    equipment: ["dumbbells", "kettlebells"],
    can_train_at_home: true,
    bodyweight: false,
    compound: true,
    unilateral: false,
  },
  {
    id: "reverse-curl",
    name: "Reverse Curl",
    description:
      "A biceps curl variation where you grip the barbell with palms facing down to engage the forearms.",
    muscleGroups: ["forearm extensors", "biceps"],
    difficulty: "intermediate",
    equipment: ["barbell", "dumbbells"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "plate-pinch",
    name: "Plate Pinch",
    description:
      "A grip-strengthening exercise where you hold weight plates together using only your fingers.",
    muscleGroups: ["forearms", "grip strength"],
    difficulty: "intermediate",
    equipment: ["weight plates"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "wrist-roller",
    name: "Wrist Roller",
    description:
      "An exercise where you roll a weighted rope up and down using wrist flexion and extension.",
    muscleGroups: ["forearm flexors", "forearm extensors"],
    difficulty: "intermediate",
    equipment: ["wrist roller"],
    can_train_at_home: false,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "towel-grip-pull-ups",
    name: "Towel Grip Pull-Ups",
    description:
      "A pull-up variation where you grip towels draped over a bar to challenge forearm and grip strength.",
    muscleGroups: ["forearms", "grip strength", "biceps", "back"],
    difficulty: "intermediate",
    equipment: ["pull-up bar", "towels"],
    can_train_at_home: true,
    bodyweight: true,
    compound: true,
    unilateral: false,
  },
  {
    id: "hand-gripper",
    name: "Hand Gripper",
    description:
      "A simple grip-strengthening exercise using a hand gripper to improve forearm endurance and strength.",
    muscleGroups: ["forearms", "grip strength"],
    difficulty: "beginner",
    equipment: ["hand gripper"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
];
