export const shoulderExercises: Exercise[] = [
  {
    id: "overhead-press",
    name: "Overhead Press",
    description:
      "A compound movement where you press a barbell or dumbbells overhead to strengthen the shoulders.",
    muscleGroups: ["deltoids", "triceps", "upper chest"],
    difficulty: "intermediate",
    equipment: ["barbell", "dumbbells"],
    can_train_at_home: true,
    bodyweight: false,
    compound: true,
    unilateral: false,
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    description:
      "An isolation exercise where you raise dumbbells out to the sides to target the lateral delts.",
    muscleGroups: ["lateral deltoids"],
    difficulty: "beginner",
    equipment: ["dumbbells"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
    importance: 1.25,
  },
  {
    id: "front-raise",
    name: "Front Raise",
    description:
      "An isolation movement where you lift dumbbells or a plate straight in front of you to target the front delts.",
    muscleGroups: ["front deltoids"],
    difficulty: "beginner",
    equipment: ["dumbbells", "weight plate"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
    importance: 0.25,
  },
  {
    id: "rear-delt-fly",
    name: "Rear Delt Fly",
    description:
      "An isolation exercise where you bend over and extend your arms outward to strengthen the rear delts.",
    muscleGroups: ["rear deltoids", "traps"],
    difficulty: "beginner",
    equipment: ["dumbbells", "cable machine"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
    image: "rear-delts.jpg",
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    description:
      "A variation of the overhead press where you rotate the dumbbells during the lift for complete shoulder activation.",
    muscleGroups: ["deltoids", "triceps", "upper chest"],
    difficulty: "intermediate",
    equipment: ["dumbbells"],
    can_train_at_home: true,
    bodyweight: false,
    compound: true,
    unilateral: false,
  },
  {
    id: "face-pull",
    name: "Face Pull",
    description:
      "A cable exercise where you pull a rope attachment toward your face to strengthen the rear delts and upper traps.",
    muscleGroups: ["rear deltoids", "traps", "rhomboids"],
    difficulty: "beginner",
    equipment: ["cable machine"],
    can_train_at_home: false,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    description:
      "A machine-based version of lateral raises that provides constant tension on the lateral delts.",
    muscleGroups: ["lateral deltoids"],
    difficulty: "beginner",
    equipment: ["cable machine"],
    can_train_at_home: false,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
];
