export const tricepsExercises: Exercise[] = [
  {
    id: "triceps-dips",
    name: "Triceps Dips",
    description:
      "A bodyweight exercise where you lower and raise yourself on parallel bars, targeting the triceps.",
    muscleGroups: ["triceps", "shoulders", "chest"],
    difficulty: "intermediate",
    equipment: ["dip bars"],
    can_train_at_home: false,
    bodyweight: true,
    compound: true,
    unilateral: false,
    importance: 0.5,
  },
  {
    id: "bench-dips",
    name: "Bench Dips",
    description:
      "A triceps exercise where you use a bench to lower and raise your body, placing emphasis on the triceps.",
    muscleGroups: ["triceps"],
    difficulty: "beginner",
    equipment: ["bench"],
    can_train_at_home: true,
    bodyweight: true,
    compound: false,
    unilateral: false,
    importance: 0.5,
  },
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    description:
      "A bench press variation where you place your hands closer together to emphasize triceps activation.",
    muscleGroups: ["triceps", "chest", "shoulders"],
    difficulty: "intermediate",
    equipment: ["barbell", "bench"],
    can_train_at_home: false,
    bodyweight: false,
    compound: true,
    unilateral: false,
  },
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    description:
      "A cable exercise where you push a bar or rope attachment down to extend your arms fully, isolating the triceps.",
    muscleGroups: ["triceps"],
    difficulty: "beginner",
    equipment: ["cable machine"],
    can_train_at_home: false,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "overhead-triceps-extension",
    name: "Overhead Triceps Extension",
    description:
      "A dumbbell or cable exercise where you extend your arms overhead, focusing on the long head of the triceps.",
    muscleGroups: ["triceps"],
    difficulty: "beginner",
    equipment: ["dumbbell", "cable machine"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "skull-crushers",
    name: "Skull Crushers",
    description:
      "A triceps isolation exercise where you lower a barbell or dumbbells toward your forehead before extending your arms.",
    muscleGroups: ["triceps"],
    difficulty: "intermediate",
    equipment: ["barbell", "dumbbells", "bench"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: false,
  },
  {
    id: "diamond-push-up",
    name: "Diamond Push-Up",
    description:
      "A push-up variation where your hands form a diamond shape under your chest to emphasize the triceps.",
    muscleGroups: ["triceps", "chest", "shoulders"],
    difficulty: "beginner",
    equipment: [],
    can_train_at_home: true,
    bodyweight: true,
    compound: true,
    unilateral: false,
    importance: 0.1,
  },
  {
    id: "kickbacks",
    name: "Triceps Kickbacks",
    description:
      "An isolation exercise where you extend your arm backward with a dumbbell to engage the triceps.",
    muscleGroups: ["triceps"],
    difficulty: "beginner",
    equipment: ["dumbbell"],
    can_train_at_home: true,
    bodyweight: false,
    compound: false,
    unilateral: true,
  },
];
